import React from 'react';
import CallToAction from './call-to-action';
import { rubikFont } from '@/styles/fonts';
import { Icons } from '@/components/icons';
import HomePageAudioWaves from './audio-waves';

const HeroSection = () => {
  return (
    <section
      className="relative h-[600px] justify-center"
      style={{
        backgroundImage: `url('/site/bg2.png')`,
        backgroundSize: 'cover', // Cover the entire section
        backgroundPosition: 'center', // Center the background image
        backgroundRepeat: 'no-repeat', // Do not repeat the image
      }}
    >
      <div className="p-8 flex flex-col justify-center ml-0 sm:ml-auto mr-0 sm:mr-12 items-center sm:items-end h-full gap-4 max-w-[600px]">
        <p
          className={`text-5xl font-bold text-center sm:text-end text-white rounded-lg p-2 ${rubikFont.className}`}
        >
          Generate Spotify playlists based on your mood within seconds
        </p>
        <CallToAction />
      </div>
      <HomePageAudioWaves />
      <div className="absolute top-0 right-0 mt-4 mr-4 text-end font-bold text-success">
        <div className="w-fit flex items-center gap-2">
          <Icons.spotify size={24} />
          Powered by Spotify API
        </div>
      </div>
      <div className="sr-only">This image was generated by AI</div>
    </section>
  );
};

export default HeroSection;
